# Copyright (c) Team CharLS.
# SPDX-License-Identifier: BSD-3-Clause

[package]
name = "charls-rs" # TODO: Identify a good package name
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
